//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Security.AccessControl;

    public partial class ekzam_MihailovaEntities : DbContext
    {
        private static ekzam_MihailovaEntities con;
        public ekzam_MihailovaEntities()
            : base("name=ekzam_MihailovaEntities")
        {
        }
    
        public static ekzam_MihailovaEntities getContext()
        {
            if (con == null)
            {
                con = new ekzam_MihailovaEntities();
            }
            return con;
        }    

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Executor> Executor { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
